### PR TITLE
cmake: Support the proper GNU-EFI include directory paths

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This pull request includes a minor fix to the project name and adds the directories for various GNU-EFI supported architectures.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Yeah, it looks like you're right about the directory paths, @vathpela introduced [this change](https://src.fedoraproject.org/rpms/gnu-efi/blob/26bd2176da634c779e3f9b20ab579856e6a2340b/f/0022-Use-EFI-canonical-names-everywhere-the-compiler-does.patch) in Fedora's `gnu-efi` some time ago.

**Comment by maharmstone** [comment]
Thanks, I have done. I had to change LANGS to LANGUAGES though or it wouldn't work (on CMake 3.28).

That Fedora change looks a little silly to me, I don't quite understand why he did that...

**Comment by Conan-Kudo** [comment]
> Thanks, I have done. I had to change LANGS to LANGUAGES though or it wouldn't work (on CMake 3.28).
> 

Oh welp.

> That Fedora change looks a little silly to me, I don't quite understand why he did that...

I think it's to make it consistent with "ia32", which is not a Linux architecture name, but an EFI architecture name. I think EDK2 also uses EFI architecture names instead, too. So this is probably a consistency thing.

**Comment by Conan-Kudo** [comment]
This is no longer needed since Fedora gnu-efi reverted back to GCC arches instead of using EFI arches for the directories.

**Pull request closed without merging**
